capacitorparty/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                path('admin/', admin.site.urls),
                path('productions/', include('productions.urls')),
                path('', include('editions.urls'))
            ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# print(urlpatterns)

editions/urls.py
from django.urls import path
from editions import views

urlpatterns = [
    path("", views.index, name="index"),
    path("index", views.index, name="index"),
    path("editions", views.editions, name="editions"),
    path("editions/<int:edition_id>/", views.edition, name="edition"),
]

productions/urls.py
from django.urls import path
from productions import views


urlpatterns = [
    path("", views.productions, name="productions"),
    path("<int:production_id>/", views.production, name="productions"),
    path("upload", views.upload, name="upload"),
    path("author/<int:author_id>/", views.author, name="author"),
]

productions/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from tinymce.models import HTMLField
from defaults.models import BaseModel
from embed_video.fields import EmbedVideoField
from upload_validator import FileTypeValidator

# Create your models here.


class Description(BaseModel):
    content = HTMLField()


class ProductionType(models.TextChoices):
    GRAPHICS = 1, "Gráficos"
    MUSIC = 2, "Música"
    DEMO = 3, "Demo"
    INTRO = 4, "Intro"
    PIXELART = 5, "Pixel Art"
    WILDCOMPO = 6, "Wild compo"
    GAMEDEV = 7, "Game development"
    INVITATION = 8, "Invitación"


class PrizeType(models.TextChoices):
    CASHPRIZE = 1, "Premio en metálico"
    GIFT = 2, "Regalo"
    COUPON = 3, "Cupón"


class Role(BaseModel):
    name = models.CharField(max_length=200)
    description = HTMLField(blank=True, null=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class OrganizerRole(BaseModel):
    name = models.CharField(max_length=200)
    description = HTMLField(blank=True, null=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Scener(BaseModel):

    """Scener model
    Proxy model that extends the user base data with Scener profile
    It's possible that scener haven't got a Django's user

    """

    user = models.OneToOneField(User, on_delete=models.SET_NULL, blank=True, null=True)
    name = models.CharField(max_length=200, unique=True)
    roles = models.ManyToManyField(Role)
    description = HTMLField(blank=True, null=True)
    external_link = models.URLField(max_length=200, blank=True, null=True)
    website = models.URLField(max_length=200, blank=True, null=True)
    avatar = models.ImageField(
        upload_to="avatars",
        blank=True,
        null=True,
    )

    def avatar_tag(self):
        from django.utils.html import mark_safe

        return mark_safe(
            '<img src="%s" width="100px" height="100px" />' % (self.avatar.url)
        )

    avatar_tag.short_description = "Image"
    avatar_tag.allow_tags = True

    def __str__(self):
        return self.name


class Organizer(BaseModel):
    name = models.CharField(max_length=200)
    roles = models.ManyToManyField(OrganizerRole)
    description = HTMLField(blank=True, null=True)

    def __str__(self):
        return self.name


class ScenersGroup(BaseModel):
    name = models.CharField(max_length=200, unique=True)
    member = models.ManyToManyField(Scener)
    description = HTMLField(blank=True, null=True)
    external_link = models.URLField(max_length=200, blank=True, null=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return "%s" % (self.name)


# class File(BaseModel):
#     name = models.CharField(max_length=200)
#     path = models.FileField(upload_to="files")
#     description = HTMLField(blank=True, null=True)

#     def __str__(self):
#         return '%s' % (self.name)


class Production(BaseModel):
    title = models.CharField(max_length=200)
    description = HTMLField(blank=True, null=True)
    group = models.ForeignKey(
        ScenersGroup, blank=True, null=True, on_delete=models.SET_NULL
    )
    production_type = models.CharField(
        max_length=2, choices=ProductionType.choices, default=ProductionType.GRAPHICS
    )
    authors = models.ManyToManyField(Scener)
    date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    # filepath = models.ForeignKey(File, on_delete=models.CASCADE, blank=True, null=True)
    filepath = models.FileField(
        validators=[
            FileTypeValidator(
                allowed_types=[
                    "application/x-amiga-disk-format",
                    "application/octet-stream",
                    "image/jpeg",
                    "image/png",
                    "application/x-tar",
                    "application/x-adf",
                    "application/x-lha",
                ]
            ),
        ],
        upload_to="files",
    )
    classification = models.IntegerField(blank=True, null=True)
    preview = models.ImageField(upload_to="pictures", blank=True, null=True)
    videolink = EmbedVideoField(max_length=200, blank=True, null=True)
    edition = models.ForeignKey(
        "editions.Edition", blank=True, null=True, on_delete=models.SET_NULL
    )

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-published_date"]


class Prize(BaseModel):
    name = models.CharField(max_length=200)
    prize_type = models.CharField(
        max_length=2, choices=PrizeType.choices, default=PrizeType.CASHPRIZE
    )
    value = models.IntegerField(blank=False)
    description = HTMLField(blank=True, null=True)

    def __str__(self):
        return "%s" % (self.name)


class Compo(BaseModel):
    name = models.CharField(max_length=200)
    rules = HTMLField(blank=True, null=True)

    def __str__(self):
        return "%s" % (self.name)

productions/forms.py
from django import forms
from productions.models import Production
from upload_validator import FileTypeValidator


class ProductionForm(forms.ModelForm):
    class Meta:
        model = Production
        fields = (
            "title",
            "description",
            "production_type",
            "filepath",
        )

        labels = {
            "title": "Título",
            "description": "Descripción",
            "production_type": "Tipo",
            "filepath": "File",
        }

        widgets = {
            "title": forms.TextInput(
                attrs={"class": "form-control", "type": "text", "placeholder": "Título"}
            ),
            "description": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "type": "text",
                    "placeholder": "Descripción",
                }
            ),
            "production_type": forms.Select(
                attrs={"class": "form-control", "placeholder": "Tipo"}
            ),
            # 'filepath': forms.TextInput(attrs = {'class':'form-control','type':'file', 'placeholder':'File'}),
            "filepath": forms.FileInput(
                attrs={
                    "accept": "image/jpeg,image/png,application/x-tar,application/x-amiga-disk-format,application/x-adf,application/x-lha",
                    "class": "form-control",
                    "type": "file",
                    "placeholder": "File",
                }
            ),
            # "filepath": forms.FileField(
            # label="",
            # help_text="Formats accepted: JPEG nd PNG",
            # required=True,
            # validators=[
            #     FileTypeValidator(allowed_types=["image/jpeg", "image/png"])
            # ],
            # ),
        }

    def __init__(self, *args, **kwargs):
        super(ProductionForm, self).__init__(*args, **kwargs)
        self.fields["production_type"].choices = [
            ("", "Elige el tipo de producción"),
        ] + list(self.fields["production_type"].choices)[1:]

productions/views.py
from django.shortcuts import render, redirect, get_object_or_404
from productions.models import ProductionType, Production, Scener, ScenersGroup
from productions.forms import ProductionForm
import inflect


# Create your views here.


def productions(request):

    productions = Production.objects.exclude(published_date__isnull=True).order_by(
        "production_type"
    )
    return render(
        request, "productions/productions.html", dict(productions=productions)
    )


def production(request, production_id):

    production = get_object_or_404(Production, pk=production_id)
    inf = inflect.engine()
    clasificacion = None
    if production.classification:
        clasificacion = inf.ordinal(production.classification)

    return render(
        request,
        "productions/production.html",
        dict(production=production, clasificacion=clasificacion),
    )


def author(request, author_id):

    author = get_object_or_404(Scener, pk=author_id)
    productions = Production.objects.filter(authors=author)

    groups = ScenersGroup.objects.filter(member=author)

    return render(
        request,
        "productions/author.html",
        dict(scener=author, groups=groups, productions=productions),
    )


def upload(request):
    """ Function to upload the production files """
    # import pdb

    if request.method == "POST":
        # pdb.set_trace()
        form = ProductionForm(request.POST, request.FILES)
        if form.is_valid():
            # print("========1=======")
            # print(request.FILES["filepath"].content_type)
            instance = Production(
                filepath=request.FILES["filepath"],
                title=request.POST["title"],
                description=request.POST["description"],
                production_type=request.POST["production_type"],
            )
            # pdb.set_trace()
            instance.save()
            return redirect("productions")
        else:
            print("========2=======")
            print(form.has_error)
            print(form.errors)
            print(request.FILES["filepath"].content_type)

        print("========3=======")
        print(request.FILES["filepath"].content_type)

    else:
        form = ProductionForm()
        # form.use_required_attribute=False
    return render(request, "productions/upload.html", dict(form=form))

capacitorparty/templates/productions/author.html
{% extends 'base/layout.html' %}
{% load filter_tags %}
{% load static %}

{% block content %}

<section class="bg-dark author">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-md-offset-3 col-md-pull-3 text-center">
                <span class="heading-meta">Scener</span>
                <span class="heading-meta-sub">Scener</span>
                <h2>{{ scener.name }}</h2>
            </div>
        </div>
    </div>
</section>

<!-- Author -->
<section class="bg-dark" id="author">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3 mb-12">
                <div class="row">
                    {% if scener.roles %}
                    <div>
                        <span>Roles:</span>
                        {% spaceless %}
                        {% for role in scener.roles.all %}
                        {% if forloop.first == False %}
                        <span>, </span><span>{{ role.name }}</span>
                        {% else %}
                        {{ role.name }}
                        {% endif %}
                        {% endfor %}
                        {% endspaceless %}
                    </div>
                    {% endif %}
                </div>
                <div class="row">
                    <div>
                        <span>Miembro de:</span>
                        <ul>
                            {% spaceless %}
                            {% for group in groups.all %}
                            <li>{{ group.name }}</li>
                            {% endfor %}
                            {% endspaceless %}
                        </ul>
                    </div>
                </div>
                <div class="row">
                    {% if scener.external_link %}
                    <div>
                        <span>Links:</span>
                        <p><a href="{{ scener.external_link }}">{{ scener.external_link }}</a></p>
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-md-8 mb-12 ">
                <div class="table-responsive">
                    <table class="table">
                        <tbody>
                            {% for production in productions %}
                            <tr>
                                <td>
                                    <a href="/productions/{{ production.id }}" class="blog-img mb-3"><img
                                            src="{{production.preview.url}}" class="img-responsive" alt=""></a>
                                    <!-- <a href="/productions/{{ production.id }}" class="blog-img"></a><img src="{{production.preview.url}}" class="img-responsive" alt=""></a> -->
                                </td>
                                <td width="80%"><a href="/productions/{{ production.id }}">{{ production.title }}</a>
                                    <p class="text-muted">
                                        <small>{{ production.get_production_type_display }}. {{ production.edition.name
                                            }}</small>
                                    </p>
                                </td>
                            </tr>
                            {% endfor %}

                        </tbody>

                    </table>

                </div>

            </div>
        </div>
    </div>
</section>
<!-- End Author -->

{% endblock %}

capacitorparty/templates/productions/production.html
{% extends 'base/layout.html' %}
{% load filter_tags %}
{% load static %}
{% load embed_video_tags %}
{% load mathfilters %}
{% block content %}

<section class="production bg-dark" id="product">
   
   <div class="container-fluid">
      <div class="row">
         <div class="col-md-12 col-md-offset-3 col-md-pull-3 text-center">
            <span class="heading-meta">Producciones</span>
            <span class="heading-meta-sub">Producciones</span>
         </div>
      </div>

      <div class="row bg-dark">
         <div class="col-md-6 mb-6">
            {% if production.videolink %}
               {% video production.videolink as videolink %}
                  {% video videolink '100% x 450' %}
               {% endvideo %}
            {% else %}
               <img src="{{production.preview.url}}" class="img-responsive" alt="">
            {% endif %}
         </div>
         <div class="col-md-6">
            <div id="sticky_item">
               <div class="desc">
                  <h2>{{ production.title }}
                     <span class="text-muted"><small>{{ production.get_production_type_display }} </small> 
                        {% if production.group %}
                           <small> by {{ production.group.name }} </small>
                        {% endif %}
                         <small>| {{ production.edition.name }} </small>
                     </span>
                  </h2>
                  <div class="content-info">
                     <div class="row item">
                        {% if classificacion %}
                        <div class="col-md-6 single-info">
                           <span >Clasificación:</span>
                           <p style="color: #00ebab; text-transform: uppercase;">{{ clasificacion }} position {{ production.get_production_type_display }} compo</p>
                        </div>
                        {% endif %}
                        <div class="col-md-6 single-info">
                           <span >Tipo:</span>
                           <p style="color: #00ebab; text-transform: uppercase;">{{ production.get_production_type_display }}</p>
                        </div>

                        <div class="col-md-6 single-info">
                           <span >Grupo:</span>
                           <p style="color: #00ebab; text-transform: uppercase;">{{ production.group.name }}</p>
                        </div>

                        <div class="col-md-6 single-info">
                           {% if production.authors.all|length > 1 %}
                              <span >Autores:</span>
                              
                           {% else %}
                              <span>Autor:</span>
                           {% endif %}
                           <br/>
                           
                           {% for author in production.authors.all %}
                              <a href="/productions/author/{{ author.id }}">{{ author.name }}</a><br/>
                           {% endfor %}
                           
                        </div>
                        <div class="col-md-6 single-info">
                           <p><a href="{{ production.filepath.url }}"><i class="icon fas fa-download"></i> {{ production.filepath.path | last_element:"/" }}</a>
                              <br/>{{ production.filepath.size | intdiv:1024 }} Kb</p>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <div class="row" style="margin:4px 2px 0 0;">  
              
         {% if production.description %}
         <div class="content-info">
            <div class="single-info">
               {{ production.description | safe}}
            </div>
         </div>
         {% endif %}
      </div>
   </div>
   
</section>

 {% endblock %}

capacitorparty/templates/productions/productions.html
{% extends 'base/layout.html' %}
{% load filter_tags %}
{% load static %}
{% block content %}
   <!-- Banner -->

   <!-- Blog -->

   <section class="blog" id="blog">
      <div class="container-fluid">
         <div class="row">
            <div class="col-md-12 col-md-offset-3 col-md-pull-3 text-center">
               <span class="heading-meta">Compos</span>
               <span class="heading-meta-sub">COMPOS</span>
               <h2>Producciones</h2>
            </div>
         </div>

         <div class="row">

            {% for production in productions %}
            <div class="col-md-4 col-sm-6">
               <div class="blog-entry">
                  <!-- <div class="date">Oct 30<br> 2019</div> -->
                  <a href="/productions/{{ production.id }}" class="blog-img"><img src="{{production.preview.url}}"  alt=""></a>
                  
                  <div style="padding: 10px 10px;">
                     <span class="text-muted"><small>{{ production.get_production_type_display }} </small> 
                        {% if production.group %}
                           <small> by {{ production.group.name }} </small>
                        {% endif %}
                        <small>| {{ production.edition.name }} </small>
                     </span>
                     <h3><a href="/productions/{{ production.id }}">{{ production.title }}</a></h3>
                     <p>
                        <small>
                        {% if production.authors.all|length > 1 %}
                           <span style="color: #00ebab; text-transform: uppercase;">Autores:</span>
                        {% else %}
                           <span style="color: #00ebab; text-transform: uppercase;">Autor:</span>
                        {% endif %}
                        </small>
                        {% spaceless %}
                        {% for author in production.authors.all %}
                        {% if forloop.first == False %}
                        <span>, </span><span><a href="/productions/author/{{ author.id }}">{{ author.name }}</a></span>
                        {% else %}
                        <span><a href="/productions/author/{{ author.id }}">{{ author.name }}</a></span>
                        {% endif %}
                        {% endfor %}
                        {% endspaceless %}
                     </p>
                  </div>
               </div>
            </div>
            {% endfor %}
         </div>
      </div>
   </section>




   <!-- End Blog -->

 {% endblock %}

capacitorparty/templates/productions/upload.html
{% extends 'base/layout.html' %}
{% load static %}
{% block content %}

 <section class="contact bg-dark" id="contact">
   <div class="container">
      <div class="row">
         <div class="col-md-12 col-md-offset-3 col-md-pull-3 text-center">
            <span class="heading-meta">Producciones</span>
            <span class="heading-meta-sub">Producciones</span>
            <h2>Envía tu producción</h2>
         </div>
      </div>
      <div class="row form-section">
         <div class="col-md-12">
            <div class="row">
               <div class="col-md-12 col-md-offset-1 col-md-pull-1">
                  <form method="post" enctype="multipart/form-data">
                     {% csrf_token %}
                     <div class="form-group">
                        {{form.title}}
                     </div>
                     <div class="form-group">
                        {{form.description}}
                     </div>
                     <div class="form-group">
                        {{form.production_type}}
                     </div>
                     <div class="form-group" >
                        {{form.filepath}}
                     </div>
                     <div class="form-group text-right">
                        <input type="submit" class="btn btn-primary btn-send-message" value="Upload">
                     </div>
                  </form>
               </div>
            </div>
         </div>
      </div>
   </div>
</section>

{% endblock %}